import type { WorkspaceCandidate, WorkspaceJd } from "./workspace-model";

const now = "2026-03-22T08:45:00+08:00";

export const mockJds: WorkspaceJd[] = [
  {
    id: "9d71d1ff-6024-4d03-95b5-95296eb4c170",
    title: "高级前端工程师",
    description:
      "负责内部招聘工作台与业务中台的前端建设，要求能独立承担复杂界面设计、状态建模和跨端体验优化。",
    requiredSkills: ["React", "Next.js", "TypeScript", "Tailwind CSS", "组件化设计"],
    bonusSkills: ["SWR", "Zustand", "可视化图表", "AI 工作流", "招聘业务理解"],
    isActive: true,
    status: "active",
    createdAt: "2026-03-18T09:00:00+08:00",
    updatedAt: now,
  },
  {
    id: "8f6fe5d2-9d55-4fb4-9d36-72fcedb0c9a0",
    title: "平台产品工程师",
    description: "聚焦数据面板和平台配置体验，目前仅保留为历史岗位。",
    requiredSkills: ["React", "数据建模", "B 端产品"],
    bonusSkills: ["实验平台", "埋点分析"],
    isActive: false,
    status: "archived",
    createdAt: "2026-03-10T09:00:00+08:00",
    updatedAt: "2026-03-15T10:20:00+08:00",
  },
];

export const mockCandidates: WorkspaceCandidate[] = [
  {
    id: "52b614f1-ff71-4e2d-8a15-d3f9f4c7f801",
    displayName: "李欣然",
    email: "lixinran@example.com",
    phone: "13800138001",
    city: "上海",
    skillTags: ["React", "Next.js", "TypeScript", "Tailwind CSS", "SWR"],
    status: "screening_passed",
    processingStatus: "ready",
    uploadedAt: "2026-03-21T10:30:00+08:00",
    updatedAt: "2026-03-22T08:20:00+08:00",
    currentScore: {
      jdId: mockJds[0].id,
      jdTitle: mockJds[0].title,
      totalScore: 91,
      skillMatchScore: 94,
      experienceRelevanceScore: 90,
      educationFitScore: 82,
      isStale: false,
      scoredAt: "2026-03-22T08:18:00+08:00",
    },
    originalFileName: "李欣然-高级前端.pdf",
    originalFilePath: "/resumes/52b614f1-ff71-4e2d-8a15-d3f9f4c7f801.pdf",
    mimeType: "application/pdf",
    fileSize: 2_684_212,
    pageCount: 3,
    profile: {
      basicInfo: {
        name: "李欣然",
        phone: "13800138001",
        email: "lixinran@example.com",
        city: "上海",
      },
      educationHistory: [
        {
          school: "同济大学",
          major: "软件工程",
          degree: "本科",
          graduationTime: "2020-06",
        },
      ],
      workExperiences: [
        {
          companyName: "某互联网平台",
          position: "高级前端工程师",
          timeRange: "2022-03 至今",
          summary: "负责招聘与协作平台，主导工作台重构、组件体系建设和性能优化。",
        },
        {
          companyName: "某 SaaS 公司",
          position: "前端工程师",
          timeRange: "2020-07 至 2022-02",
          summary: "负责 B 端报表系统、权限中心和低代码表单搭建。",
        },
      ],
      skillTags: ["React", "Next.js", "TypeScript", "Tailwind CSS", "SWR", "Zustand"],
      projectExperiences: [
        {
          projectName: "招聘工作台升级",
          techStack: ["Next.js", "SWR", "Tailwind CSS"],
          responsibilities: ["重构信息架构", "搭建候选人三栏工作台", "落地筛选与详情联动"],
          highlights: ["首屏操作路径缩短", "统一候选人和 JD 对照心智"],
        },
      ],
      sourceText: "源文本已省略",
      cleanedText: "清洗文本已省略",
      extractionNotes: "结构化信息完整，可直接进入人工筛选。",
      extractedAt: "2026-03-22T08:12:00+08:00",
    },
    rawText: "源文本已省略",
    cleanedText: "清洗文本已省略",
    scores: [
      {
        id: "8e245933-c63e-4d0c-89e4-7155719a8fe2",
        candidateId: "52b614f1-ff71-4e2d-8a15-d3f9f4c7f801",
        jdId: mockJds[0].id,
        jdTitle: mockJds[0].title,
        totalScore: 91,
        skillMatchScore: 94,
        experienceRelevanceScore: 90,
        educationFitScore: 82,
        aiCommentary:
          "在 React 与 Next.js 项目中的主导经验较强，组件化和工作台改版能力与目标岗位高度匹配。",
        scoreDetails: {
          skillNotes: "React、Next.js、TypeScript 与岗位必备技能高度匹配。",
          experienceNotes: "具备招聘工作台升级和 B 端系统改造经验，经验相关性较高。",
          educationNotes: "本科背景满足岗位要求，专业方向与前端研发相关。",
          matchedSkills: ["React", "Next.js", "TypeScript", "Tailwind CSS"],
          missingSkills: [],
        },
        isStale: false,
        scoredAt: "2026-03-22T08:18:00+08:00",
      },
    ],
    previewUrl: null,
  },
  {
    id: "6c3e0c8b-6bdd-48d5-bdb6-6d08d1a6cc31",
    displayName: "赵嘉禾",
    email: "zhaojiahe@example.com",
    phone: "13800138002",
    city: "杭州",
    skillTags: ["React", "TypeScript", "数据可视化", "ECharts"],
    status: "pending_review",
    processingStatus: "scoring",
    uploadedAt: "2026-03-22T07:56:00+08:00",
    updatedAt: "2026-03-22T08:35:00+08:00",
    currentScore: null,
    originalFileName: "赵嘉禾-前端.pdf",
    originalFilePath: "/resumes/6c3e0c8b-6bdd-48d5-bdb6-6d08d1a6cc31.pdf",
    mimeType: "application/pdf",
    fileSize: 1_984_220,
    pageCount: 2,
    profile: {
      basicInfo: {
        name: "赵嘉禾",
        phone: "13800138002",
        email: "zhaojiahe@example.com",
        city: "杭州",
      },
      educationHistory: [
        {
          school: "浙江大学",
          major: "计算机科学与技术",
          degree: "硕士",
          graduationTime: "2021-06",
        },
      ],
      workExperiences: [
        {
          companyName: "某金融科技公司",
          position: "前端工程师",
          timeRange: "2021-07 至今",
          summary: "主导数据大屏和分析系统，熟悉复杂状态管理与图表交互。",
        },
      ],
      skillTags: ["React", "TypeScript", "数据可视化", "ECharts"],
      projectExperiences: [],
      sourceText: "源文本已省略",
      cleanedText: "清洗文本已省略",
      extractionNotes: "简历已解析完成，当前正在进行与活动 JD 的评分。",
      extractedAt: "2026-03-22T08:05:00+08:00",
    },
    rawText: "源文本已省略",
    cleanedText: "清洗文本已省略",
    scores: [],
    previewUrl: null,
  },
  {
    id: "fb6548dc-f41f-4d58-aa12-a61f7dbce9a8",
    displayName: "陈诺",
    email: null,
    phone: null,
    city: "北京",
    skillTags: ["Vue", "Node.js"],
    status: "rejected",
    processingStatus: "failed",
    uploadedAt: "2026-03-20T18:20:00+08:00",
    updatedAt: "2026-03-20T18:42:00+08:00",
    currentScore: null,
    originalFileName: "陈诺-简历.pdf",
    originalFilePath: "/resumes/fb6548dc-f41f-4d58-aa12-a61f7dbce9a8.pdf",
    mimeType: "application/pdf",
    fileSize: 1_221_184,
    pageCount: 1,
    profile: null,
    rawText: null,
    cleanedText: null,
    scores: [],
    previewUrl: null,
  },
];
